In [143]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [144]:
df = pd.read_csv('Wine.csv')

In [145]:
df

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [146]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [153]:
df_X = df.drop(['Customer_Segment'], axis = 1)

In [173]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [174]:
corr_mat = df_X.corr()

In [175]:
corr_mat

Alcohol  Malic_Acid       Ash  Ash_Alcanity  Magnesium  \
Alcohol               1.000000    0.094397  0.211545     -0.310235   0.270798   
Malic_Acid            0.094397    1.000000  0.164045      0.288500  -0.054575   
Ash                   0.211545    0.164045  1.000000      0.443367   0.286587   
Ash_Alcanity         -0.310235    0.288500  0.443367      1.000000  -0.083333   
Magnesium             0.270798   -0.054575  0.286587     -0.083333   1.000000   
Total_Phenols         0.289101   -0.335167  0.128980     -0.321113   0.214401   
Flavanoids            0.236815   -0.411007  0.115077     -0.351370   0.195784   
Nonflavanoid_Phenols -0.155929    0.292977  0.186230      0.361922  -0.256294   
Proanthocyanins       0.136698   -0.220746  0.009652     -0.197327   0.236441   
Color_Intensity       0.546364    0.248985  0.258887      0.018732   0.199950   
Hue                  -0.071747   -0.561296 -0.074667     -0.273955   0.055398   
OD280                 0.072343   -0.368710  0.003911     -0.276769   0.066004   
Proline               0.643720   -0.192011  0.223626     -0.440597   0.393351   

                      Total_Phenols  Flavanoids  Nonflavanoid_Phenols  \
Alcohol                    0.289101    0.236815             -0.155929   
Malic_Acid                -0.335167   -0.411007              0.292977   
Ash                        0.128980    0.115077              0.186230   
Ash_Alcanity              -0.321113   -0.351370              0.361922   
Magnesium                  0.214401    0.195784             -0.256294   
Total_Phenols              1.000000    0.864564             -0.449935   
Flavanoids                 0.864564    1.000000             -0.537900   
Nonflavanoid_Phenols      -0.449935   -0.537900              1.000000   
Proanthocyanins            0.612413    0.652692             -0.365845   
Color_Intensity           -0.055136   -0.172379              0.139057   
Hue                        0.433681    0.543479             -0.262640   
OD280                      0.699949    0.787194             -0.503270   
Proline                    0.498115    0.494193             -0.311385   

                      Proanthocyanins  Color_Intensity       Hue     OD280  \
Alcohol                      0.136698         0.546364 -0.071747  0.072343   
Malic_Acid                  -0.220746         0.248985 -0.561296 -0.368710   
Ash                          0.009652         0.258887 -0.074667  0.003911   
Ash_Alcanity                -0.197327         0.018732 -0.273955 -0.276769   
Magnesium                    0.236441         0.199950  0.055398  0.066004   
Total_Phenols                0.612413        -0.055136  0.433681  0.699949   
Flavanoids                   0.652692        -0.172379  0.543479  0.787194   
Nonflavanoid_Phenols        -0.365845         0.139057 -0.262640 -0.503270   
Proanthocyanins              1.000000        -0.025250  0.295544  0.519067   
Color_Intensity             -0.025250         1.000000 -0.521813 -0.428815   
Hue                          0.295544        -0.521813  1.000000  0.565468   
OD280                        0.519067        -0.428815  0.565468  1.000000   
Proline                      0.330417         0.316100  0.236183  0.312761   

                       Proline  
Alcohol               0.643720  
Malic_Acid           -0.192011  
Ash                   0.223626  
Ash_Alcanity         -0.440597  
Magnesium             0.393351  
Total_Phenols         0.498115  
Flavanoids            0.494193  
Nonflavanoid_Phenols -0.311385  
Proanthocyanins       0.330417  
Color_Intensity       0.316100  
Hue                   0.236183  
OD280                 0.312761  
Proline               1.000000

In [176]:
eig_value, eig_vector = np.linalg.eig(corr_mat)

In [177]:
eig_value

array([4.70585025, 2.49697373, 1.44607197, 0.91897392, 0.85322818,
       0.64165703, 0.55102831, 0.34849736, 0.10337794, 0.16877023,
       0.28887994, 0.22578864, 0.25090248])

In [178]:
eig_vector

array([[-0.1443294 , -0.48365155,  0.20738262, -0.0178563 ,  0.26566365,
        -0.21353865, -0.05639636,  0.39613926,  0.01496997,  0.26628645,
        -0.50861912, -0.22591696,  0.21160473],
       [ 0.24518758, -0.22493093, -0.08901289,  0.53689028, -0.03521363,
        -0.53681385,  0.42052391,  0.06582674,  0.02596375, -0.12169604,
         0.07528304,  0.07648554, -0.30907994],
       [ 0.00205106, -0.31606881, -0.6262239 , -0.21417556,  0.14302547,
        -0.15447466, -0.14917061, -0.17026002, -0.14121803,  0.04962237,
         0.30769445, -0.49869142, -0.02712539],
       [ 0.23932041,  0.0105905 , -0.61208035,  0.06085941, -0.06610294,
         0.10082451, -0.28696914,  0.42797018,  0.09168285,  0.05574287,
        -0.20044931,  0.47931378,  0.05279942],
       [-0.14199204, -0.299634  , -0.13075693, -0.35179658, -0.72704851,
        -0.03814394,  0.3228833 , -0.15636143,  0.05677422, -0.06222011,
        -0.27140257,  0.07128891,  0.06787022],
       [-0.39466085, -0.065039

In [179]:
total = 0
var_sum = sum(eig_value)
var = []
for item in eig_value:
  L = (item/var_sum) * 100
  total = total + L

  if total < 75:
    var.append(L)
  else:
    break

In [180]:
var

[36.19884809992631, 19.207490257008946, 11.123630536249996, 7.069030182714024]

In [181]:
W = eig_vector[0:13, 0:4]

In [182]:
W

array([[-0.1443294 , -0.48365155,  0.20738262, -0.0178563 ],
       [ 0.24518758, -0.22493093, -0.08901289,  0.53689028],
       [ 0.00205106, -0.31606881, -0.6262239 , -0.21417556],
       [ 0.23932041,  0.0105905 , -0.61208035,  0.06085941],
       [-0.14199204, -0.299634  , -0.13075693, -0.35179658],
       [-0.39466085, -0.06503951, -0.14617896,  0.19806835],
       [-0.4229343 ,  0.00335981, -0.1506819 ,  0.15229479],
       [ 0.2985331 , -0.02877949, -0.17036816, -0.20330102],
       [-0.31342949, -0.03930172, -0.14945431,  0.39905653],
       [ 0.0886167 , -0.52999567,  0.13730621,  0.06592568],
       [-0.29671456,  0.27923515, -0.08522192, -0.42777141],
       [-0.37616741,  0.16449619, -0.16600459,  0.18412074],
       [-0.28675223, -0.36490283,  0.12674592, -0.23207086]])

In [183]:
new_X = np.dot(X, W) 

In [184]:
new_X

array([[-3.31675081e+00, -1.44346263e+00,  1.65739045e-01,
        -2.15631188e-01],
       [-2.20946492e+00,  3.33392887e-01,  2.02645737e+00,
        -2.91358318e-01],
       [-2.51674015e+00, -1.03115130e+00, -9.82818670e-01,
         7.24902309e-01],
       [-3.75706561e+00, -2.75637191e+00,  1.76191842e-01,
         5.67983308e-01],
       [-1.00890849e+00, -8.69830821e-01, -2.02668822e+00,
        -4.09765788e-01],
       [-3.05025392e+00, -2.12240111e+00,  6.29395827e-01,
        -5.15637495e-01],
       [-2.44908967e+00, -1.17485013e+00,  9.77094891e-01,
        -6.58305046e-02],
       [-2.05943687e+00, -1.60896307e+00, -1.46281883e-01,
        -1.19260801e+00],
       [-2.51087430e+00, -9.18070957e-01,  1.77096903e+00,
         5.62703612e-02],
       [-2.75362819e+00, -7.89437674e-01,  9.84247490e-01,
         3.49381568e-01],
       [-3.47973668e+00, -1.30233324e+00,  4.22735217e-01,
         2.68417600e-02],
       [-1.75475290e+00, -6.11977229e-01,  1.19087832e+00,
      